import { createTool } from '@mastra/core/tools';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Tool B: createNewAgent
// Dynamically provisions and registers a new agent specification if no
// existing repository agent fits the workflow task. Returns a structured
// agent definition ready to be wired into a canvas workflow.
// ---------------------------------------------------------------------------

/** Supported model providers in the AWAS platform. */
const MODEL_PROVIDERS = [
  'google',
  'openai',
  'anthropic',
  'meta',
  'mistral',
  'groq',
  'ollama',
] as const;

/** Recommended model identifiers per provider. */
const RECOMMENDED_MODELS: Record<string, string> = {
  google: 'gemini-2.0-flash',
  openai: 'gpt-4o-mini',
  anthropic: 'claude-3-5-haiku-latest',
  meta: 'llama-3.2-11b-vision-preview',
  mistral: 'mistral-small-latest',
  groq: 'llama-3.1-8b-instant',
  ollama: 'llama3.2',
};

/** Derive a kebab-case agent ID from a display name. */
function toAgentId(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Build a TypeScript source scaffold for the new agent. */
function buildAgentScaffold(spec: {
  id: string;
  name: string;
  description: string;
  instructions: string;
  modelProvider: string;
  modelId: string;
  tools: string[];
}): string {
  const toolImports = spec.tools.length > 0
    ? spec.tools.map((t) => `// import { ${t} } from '../tools/${t}-tool';`).join('\n') + '\n'
    : '';

  const toolsRecord = spec.tools.length > 0
    ? `{ ${spec.tools.map((t) => `/* ${t} */`).join(', ')} }`
    : '{}';

  return `import { Agent } from '@mastra/core/agent';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { defaultMemory } from '../memory';
import { requestContextSchema } from '../context';
import { TokenLimiter, EnsureFinalResponseProcessor, UsageTrackerProcessor } from '../processors';
import { defaultTracingPolicy } from '../observability';
${toolImports}
// ── ${spec.name} ──────────────────────────────────────────────────────────────
// Auto-generated by Studio Chat Co-Pilot  •  AWAS createNewAgent tool

const INSTRUCTIONS = \`${spec.instructions}\`;

export const ${toCamelCase(spec.id)} = new Agent({
  id: '${spec.id}',
  name: '${spec.name}',
  description: '${spec.description.replace(/'/g, "\\'")}',
  memory: defaultMemory,
  requestContextSchema,

  instructions: INSTRUCTIONS,

  model: createGoogleGenerativeAI()('${spec.modelId}'),

  tools: ${toolsRecord},

  inputProcessors: [
    new TokenLimiter(8192),
    new EnsureFinalResponseProcessor(10),
  ],
  outputProcessors: [
    new UsageTrackerProcessor(),
  ],

  options: {
    tracingPolicy: defaultTracingPolicy,
  },
});
`;
}

/** Convert kebab-case to camelCase for export names. */
function toCamelCase(id: string): string {
  return id.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Agent';
}

export const createNewAgentTool = createTool({
  id: 'create_new_agent',
  description:
    'Dynamically provisions and registers a new AWAS agent specification when no existing agent satisfies the workflow requirement. ' +
    'Returns a ready-to-use agent definition including ID, system instructions, model config, and a TypeScript scaffold. ' +
    'IMPORTANT: Always call "list_repository_agents" first to confirm no existing agent already covers the use-case.',

  inputSchema: z.object({
    name: z
      .string()
      .min(3)
      .describe('Human-readable agent name (e.g. "Invoice Parser Agent")'),
    description: z
      .string()
      .min(10)
      .describe('Clear one-sentence description of what this agent does'),
    instructions: z
      .string()
      .min(20)
      .describe(
        'Full system-prompt / instruction set for the agent. Be specific and deterministic.',
      ),
    tools: z
      .array(z.string())
      .default([])
      .describe(
        'List of tool IDs to attach to the agent (e.g. ["pdf-tool", "slack-tool"]). ' +
        'Must match IDs of tools already registered in the AWAS repository.',
      ),
    modelProvider: z
      .enum(MODEL_PROVIDERS)
      .default('google')
      .describe('LLM provider to use for this agent.'),
    modelId: z
      .string()
      .optional()
      .describe(
        'Specific model ID override (e.g. "gemini-2.0-flash"). ' +
        'When omitted, the recommended model for the chosen provider is used.',
      ),
    temperature: z
      .number()
      .min(0)
      .max(2)
      .default(0.3)
      .describe('LLM sampling temperature (0 = deterministic, 1 = creative).'),
    maxTokens: z
      .number()
      .int()
      .min(256)
      .max(32768)
      .default(4096)
      .describe('Maximum output tokens for a single LLM response.'),
    tags: z
      .array(z.string())
      .default([])
      .describe('Capability tags to attach to this agent for future discovery (e.g. ["invoice", "finance"]).'),
  }),

  outputSchema: z.object({
    agentId: z.string().describe('Auto-generated kebab-case unique agent ID'),
    agentName: z.string(),
    description: z.string(),
    modelProvider: z.string(),
    modelId: z.string(),
    temperature: z.number(),
    maxTokens: z.number(),
    tools: z.array(z.string()),
    tags: z.array(z.string()),
    filePath: z.string().describe('Relative file path where the agent scaffold should be saved'),
    scaffoldCode: z.string().describe('Ready-to-save TypeScript source code for the new agent'),
    registrationHint: z.string().describe('Instructions to register the agent in src/mastra/index.ts'),
    status: z.enum(['created', 'error']),
    message: z.string(),
  }),

  execute: async (input) => {
    try {
      const agentId = toAgentId(input.name);
      const resolvedModelId =
        input.modelId ?? RECOMMENDED_MODELS[input.modelProvider] ?? 'gemini-2.0-flash';

      const scaffoldCode = buildAgentScaffold({
        id: agentId,
        name: input.name,
        description: input.description,
        instructions: input.instructions,
        modelProvider: input.modelProvider,
        modelId: resolvedModelId,
        tools: input.tools,
      });

      const filePath = `src/mastra/agents/${agentId}.ts`;

      const registrationHint = [
        `// 1. Save the scaffold to: ${filePath}`,
        `// 2. In src/mastra/index.ts add the import:`,
        `//    import { ${toCamelCase(agentId)} } from './agents/${agentId}';`,
        `// 3. Add it to the allAgents registry:`,
        `//    '${agentId}': ${toCamelCase(agentId)},`,
      ].join('\n');

      return {
        agentId,
        agentName: input.name,
        description: input.description,
        modelProvider: input.modelProvider,
        modelId: resolvedModelId,
        temperature: input.temperature,
        maxTokens: input.maxTokens,
        tools: input.tools,
        tags: input.tags,
        filePath,
        scaffoldCode,
        registrationHint,
        status: 'created' as const,
        message:
          `Agent "${input.name}" specification generated successfully. ` +
          `Save the scaffold to "${filePath}" and follow the registrationHint to activate it.`,
      };
    } catch (err) {
      return {
        agentId: '',
        agentName: input.name,
        description: input.description,
        modelProvider: input.modelProvider,
        modelId: input.modelId ?? '',
        temperature: input.temperature,
        maxTokens: input.maxTokens,
        tools: input.tools,
        tags: input.tags,
        filePath: '',
        scaffoldCode: '',
        registrationHint: '',
        status: 'error' as const,
        message: `Failed to create agent: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  },
});
